import React from 'react'
import ReactDOM from 'react-dom/client'
import { restaurants } from "./constants/constants";

const rootElement = document.getElementById("root");
const root = ReactDOM.createRoot(rootElement);
root.render(
  <ul>
    <li>
      <h2>{restaurants[0].name}</h2>
      <h3>Меню</h3>
      <ul>
        <li>
          <h4>{restaurants[0].menu[0].name}</h4>
          <ul>
            <li>{restaurants[0].menu[0].ingredients[0]}</li>
            <li>{restaurants[0].menu[0].ingredients[1]}</li>
          </ul>
          <p>{restaurants[0].menu[0].price}</p>
        </li>
        <li>
          <h4>{restaurants[0].menu[1].name}</h4>
          <ul>
            <li>{restaurants[0].menu[1].ingredients}</li>
          </ul>
          <p>{restaurants[0].menu[1].price}</p>
        </li>
        <li>
          <h4>{restaurants[0].menu[2].name}</h4>
          <ul>
            <li>{restaurants[0].menu[2].ingredients[0]}</li>
            <li>{restaurants[0].menu[2].ingredients[1]}</li>
          </ul>
          <p>{restaurants[0].menu[2].price}</p>
        </li>
      </ul>
      <h3>Отзывы</h3>
      <ul>
        <li>
          <h4>{restaurants[0].reviews[0].user}</h4>
          <p>{restaurants[0].reviews[0].text}</p>
          <h5>{restaurants[0].reviews[0].rating}</h5>
        </li>
        <li>
          <h4>{restaurants[0].reviews[1].user}</h4>
          <p>{restaurants[0].reviews[1].text}</p>
          <h5>{restaurants[0].reviews[1].rating}</h5>
        </li>
      </ul>
    </li>
    <li>
      <h2>{restaurants[1].name}</h2>
      <h3>Меню</h3>
      <ul>
        <li>
          <h4>{restaurants[1].menu[0].name}</h4>
          <ul>
            <li>{restaurants[1].menu[0].ingredients[0]}</li>
            <li>{restaurants[1].menu[0].ingredients[1]}</li>
            <li>{restaurants[1].menu[0].ingredients[2]}</li>
          </ul>
          <p>{restaurants[1].menu[0].price}</p>
        </li>
        <li>
          <h4>{restaurants[1].menu[1].name}</h4>
          <ul>
            <li>{restaurants[1].menu[1].ingredients[0]}</li>
            <li>{restaurants[1].menu[1].ingredients[1]}</li>
            <li>{restaurants[1].menu[1].ingredients[2]}</li>
            <li>{restaurants[1].menu[1].ingredients[3]}</li>
          </ul>
          <p>{restaurants[1].menu[1].price}</p>
        </li>
      </ul>
      <h3>Отзывы</h3>
      <ul>
        <li>
          <h4>{restaurants[1].reviews[0].user}</h4>
          <p>{restaurants[1].reviews[0].text}</p>
          <h5>{restaurants[1].reviews[0].rating}</h5>
        </li>
        <li>
          <h4>{restaurants[1].reviews[1].user}</h4>
          <p>{restaurants[1].reviews[1].text}</p>
          <h5>{restaurants[1].reviews[1].rating}</h5>
        </li>
        <li>
          <h4>{restaurants[1].reviews[2].user}</h4>
          <p>{restaurants[1].reviews[2].text}</p>
          <h5>{restaurants[1].reviews[2].rating}</h5>
        </li>
      </ul>
    </li>
    <li>
      <h2>{restaurants[2].name}</h2>
      <h3>Меню</h3>
      <ul>
        <li>
          <h4>{restaurants[2].menu[0].name}</h4>
          <ul>
            <li>{restaurants[2].menu[0].ingredients}</li>
          </ul>
          <p>{restaurants[2].menu[0].price}</p>
        </li>
        <li>
          <h4>{restaurants[2].menu[1].name}</h4>
          <ul>
            <li>{restaurants[2].menu[1].ingredients[0]}</li>
            <li>{restaurants[2].menu[1].ingredients[1]}</li>
          </ul>
          <p>{restaurants[2].menu[1].price}</p>
        </li>
        <li>
          <h4>{restaurants[2].menu[2].name}</h4>
          <ul>
            <li>{restaurants[2].menu[2].ingredients}</li>
          </ul>
          <p>{restaurants[2].menu[2].price}</p>
        </li>
      </ul>
      <h3>Отзывы</h3>
      <ul>
        <li>
          <h4>{restaurants[2].reviews[0].user}</h4>
          <p>{restaurants[2].reviews[0].text}</p>
          <h5>{restaurants[2].reviews[0].rating}</h5>
        </li>
      </ul>
    </li>
    <li>
      <h2>{restaurants[3].name}</h2>
      <h3>Меню</h3>
      <ul>
        <li>
          <h4>{restaurants[3].menu[0].name}</h4>
          <ul>
            <li>{restaurants[3].menu[0].ingredients}</li>
          </ul>
          <p>{restaurants[3].menu[0].price}</p>
        </li>
        <li>
          <h4>{restaurants[3].menu[1].name}</h4>
          <ul>
            <li>{restaurants[3].menu[1].ingredients[0]}</li>
            <li>{restaurants[3].menu[1].ingredients[1]}</li>
          </ul>
          <p>{restaurants[3].menu[1].price}</p>
        </li>
      </ul>
      <h3>Отзывы</h3>
      <ul>
        <li>
          <h4>{restaurants[3].reviews[0].user}</h4>
          <p>{restaurants[3].reviews[0].text}</p>
          <h5>{restaurants[3].reviews[0].rating}</h5>
        </li>
        <li>
          <h4>{restaurants[3].reviews[1].user}</h4>
          <p>{restaurants[3].reviews[1].text}</p>
          <h5>{restaurants[3].reviews[1].rating}</h5>
        </li>
      </ul>
    </li>
  </ul>
);

